#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  webapp:
    build:
      dockerfile: ./.devcontainer/Dockerfile
    environment:
      - ASPNETCORE_HTTPS_PORT=${HOST_HTTPS_PORT} # So that the application's HTTP to HTTPS redirection works as intended.
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ./src/WebApp/:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    ports:
      - "${HOST_HTTP_PORT}:5000"
      - "${HOST_HTTPS_PORT}:5001"