version: '3'

services:

### Web Application Container #######################
    webapp:
      build:
        context: .
        dockerfile: ./.docker/WebApp/Dockerfile
        args:
          - entrypointfile=./.docker/WebApp/docker-entrypoint.sh
          - buildconfig=${BUILD_CONFIG}
          - pathtoproject=${PATH_TO_PROJECT}
          - csprojbasename=${CS_PROJ_BASE_NAME}
          - launchapp=${LAUNCH_APP}
          # For HTTPS support:
          #   https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-3.1#windows-using-linux-containers
          - usehttpsendpoint=${USE_HTTPS_ENDPOINT}
          - autoselfsigncert=${AUTO_SELF_SIGN_CERT}
          - autoselfsigncertpassword=${AUTO_SELF_SIGN_CERT_PASSWORD}
      environment:
        - ASPNETCORE_HTTPS_PORT=${HOST_HTTPS_PORT}
      ports:
        - "${HOST_HTTP_PORT}:80"
        - "${HOST_HTTPS_PORT}:443"